import { Container } from "@/components/Container";
import { Header } from "@/components/Header";
import { QueryClientProviderChildren } from "@/providers/QueryClient.provider";
import { SonnerToast } from "@/providers/SonnerToast.provider";
import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";

const manropeFont = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ProductsNext",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manropeFont.variable} antialiased`}>
        <QueryClientProviderChildren>
          <Container>
            <Header />
            <section>{children}</section>
            <SonnerToast />
          </Container>
        </QueryClientProviderChildren>
      </body>
    </html>
  );
}
